future: true
paginate: 10
#pygments: true

highlighter: pygments
markdown: kramdown

tag_page_dir: tag
tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed
#permalink: /:year/:month/:day/:title/
url: http://panke.me
exclude: [README.md]
gems: [jekyll-paginate]

paginate_path: "page:num"
layout: post
#permalink: /:categories/:title
excerpt_separator: "[-----]"

